---
title             : "EDLD 610_final"
shorttitle        : "Title"

author: 
  - name          : "Asha"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Joanna"
    affiliation   : "1"
    corresponding : no    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Thuy"
    affiliation   : "1"
    corresponding : no    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
library(tidyverse)
library(rio)
library(here)
library(janitor)
library(dplyr)

```

```{r loading the data}

data <- import(here("data","F00007762-WV6_Data_R_v20180912.rds")) %>%
  janitor::clean_names() %>%
  select("v10", "v11", "v24", "v25", "v57", "v147", "v237", "v240") %>% 
  characterize()
# 1.Strength: As you import data, you use select and characterize function which make dataset more tidy from the initial stage.(Woocheol Kim) 
  

```

```{r renaming variable names}

data <- data %>%
  as_tibble() %>%
    rename(
      feeling_of_happiness = v10, 
      state_of_health = v11, 
      most_people_trusted = v24,
      member_religion = v25,
      marital_status = v57,
      religious_person = v147,
      family_savings = v237,
      gender = v240)

```


```{r cleaning the data step 1: collapsing v10 levels}

# I used this to view the levels of v10. v10 is a character, not a factor, so need to use unique rather than levels function. I used this to get the exact spelling of the levels in order to collapse them. 

unique(data$feeling_of_happiness)
# 1. What I've learned: Great use of 'unique' function! I've had hard time finding the correct spelling of the levels and made typo most of the time. It should help me a lot in the future because I can just copy and paste when I recode or filter.(Woocheol Kim)

# 1. You may improve: Since you already rename 'v10' to 'feeling_of_hapiness' in the previous chunk, I think it would work better if you use 'feeling_of_hapiness' instead of 'v10' in unique function. I also edit it. (Woocheol Kim)

data %>%
  mutate(feeling_of_happiness = fct_recode(feeling_of_happiness,
                          "Very happy" = "Very happy",
                          "Rather happy" = "Rather happy",
                          "Not very happy" = "Not very happy",
                          "Not at all happy" = "Not at all happy",
                          "Other" = "No answer",
                          "Other" = "Dont know", 
                          "Other" = "HT: Missing-Dropped out survey; RU: Inappropriate response{Inappropriate}"),
         state_of_health = fct_recode(state_of_health,
         "Very good" = "Very good",
                          "Good" = "Good",
                          "Faid" = "Fair",
                          "Poor" = "Poor",
                          "Other" = "No answer",
                          "Other" = "Dont know", 
                          "Other" = "BH:Missing;HT:Missing-Dropped out survey; RU:Inappropriate response{Inappropriate}"),
         most_people_trusted = fct_recode(most_people_trusted, 
                           "Most people can be trusted" = "Most people can be trusted",
                          "Need to be very careful" = "Need to be very careful",
                          "Other" = " DE,SE: Inapplicable;RU: Inappropiate response;SG:Missing;HT: Dropped out survey",
                          "Other" = "Not asked in survey",
                          "Other" = "Not applicable",
                          "Other" = "No answer",
                          "Other" = "Don´t know"),
         member_religion = fct_recode(member_religion, 
                          "Not a member" = "Not a member",
                        "Inactive member" = "Inactive member",
                        "Active member" = "Active member",
                        "Other" = " HT: Dropped out survey;SE: Inapplicable;RU: Inappropriate response",
                        "Other" = "Not asked in survey",
                        "Other" = "Not applicable",
                        "Other" = "No answer",
                        "Other" = "Don't know"), 
         marital_status = fct_recode(marital_status, 
                          "Married" = "Married",
                          "Living together as married" = "Living together as married",
                          "Divorced" = "Divorced",
                          "Separated" = "Separated",
                          "Widowed" = "Widowed",
                          "Single" = "Single",
                          "Other" = "HT: Dropped out survey;SG: Missing; RU: Inappropriate response",
                          "Other" = "Not asked in survey",
                          "Other" = "Not applicable",
                          "Other" = "No answer",
                          "Other" = "Don´t know"),
         religious_person = fct_recode(religious_person, 
                           "A religious person" = "A religious person",
                           "Not a religious person" = "Not a religious person",
                           "Not a religious person" = "An atheist",
                           "Other" = "No answer",
                           "Other" = "Dont know",
                           "Other" = "Not asked in survey",
                           "Other" = "DE,SE:Inapplicable ; RU:Inappropriate response; HT: Dropped out survey{Inappropriate}"),
         family_savings = fct_recode(family_savings, 
                           "Save money" = "Save money", 
                            "Just get by" = "Just get by", 
                            "Spent savings and borrowed money" = "Spent savings and borrowed money",
                            "Spent some savings and borrowed money" = "Spent some savings and borrowed money",
                            "Other" = "No answer",
                            "Other" = "Dont know", 
                            "Other" = "DE,SE:Inapplicable ; RU:Inappropriate response; BH: Missing; HT: Dropped out survey{Inappropriate}", 
                            "Other" = "Not applicable"),
         gender = fct_recode(gender,
                           "Male" = "Male", 
                           "Female" = "Female", 
                           "Other" = "No answer", 
                           "Other" = "Missing; Unknown")
         
         )
# 2. Strength: Using fct_recode fuction, you reduce the number of observations in each column. It will facilitate you to show the difference between group more clearly and more distictively.(Woocheol Kim)


```


```{r cleaning feeling_of_happiness variable}

# NOTE: higher value = more happy, lower value = less happy

data <- data %>% 
  mutate(feeling_of_happiness = fct_recode(feeling_of_happiness,
                          "4" = "Very happy",
                          "3" = "Rather happy",
                          "2" = "Not very happy",
                          "1" = "Not at all happy",
                          "0" = "Other")) %>%
    filter(feeling_of_happiness == "4" |
           feeling_of_happiness == "3" |
           feeling_of_happiness == "2" |
           feeling_of_happiness == "1") 

# I edit 'data %>%' to 'data <- data %>%' so you save and see the updated data.(Woocheol Kim)  


# Next step here: we need to figure out how to convert the happiness variable to an integer. Relabling didn't do this, it's still a factor. QUESTION: How do we convert this into an integer? When I try using as.numeric, it keeps coming up with an error message that the object feeling_of_happiness is not found and I don't understand why.  

# 2. You may improve: The below code is my answer for the above question about converting 'feeling_of_happiness' to integer. It seems there is a specific condition you can use as.numeric function without error.(Woocheol Kim)

# converting factor to numeric: data <- data %>% transform(data, feeling_of_happiness=as.numeric(as.character(feeling_of_happiness)))(Woocheol Kim)
  
# 3. Strength: The step-by-step work you've done is easy for reviewers like me to understand how you have developed your project so far. I've never lost as I review your work. Well done and good work!(Woocheol Kim)


```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
